### ISSUE TITLE
ERROR! the role 'harbor' was not found

### ISSUE THREAD

**Issue by patsevanton** [nicholasamorim/ansible-role-harbor#18]
Hello!
I try install harbor and get error
```
ERROR! the role 'harbor' was not found in /home/user/github/infrastructure-as-a-code-example/12-harbor/roles:/home/user/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/user/github/infrastructure-as-a-code-example/12-harbor

The error appears to be in '/home/user/github/infrastructure-as-a-code-example/12-harbor/playbook.yml': line 20, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - harbor
      ^ here
```

I install role
```
ansible-galaxy install nicholasamorim.harbor
```

Playbook
```
---
- name: Installing and configuring Harbor
  hosts: harbor
  vars:
    harbor_projects:
      - project_name: myproject
        is_public: "false"
        content_trust: "false"
        prevent_vul: "true"
        severity: "high"
        auto_scan: "true"
    harbor_users:
      - username: user1
        email: user1@test.com
        realname: User Number 1
        role_name: developer
        role_id: 2
        has_admin_role: true
  roles:
    - harbor
```
