### ISSUE TITLE
Too permissive permissions?

### ISSUE THREAD

**Issue by ghost** [nicholasamorim/ansible-role-harbor#4]
By default, things are created with             "mode": "0755"
This could be changed to 0750 I believe.

**Comment by nicholasamorim** [comment]
I'll try this today. 

I'm having quite the struggle with permissions on Harbor, because if I set user/gid 10000 to own the files but don't open the permissions, then Nginx has trouble reading `nginx/nginx.conf`.

I'm doing a fresh run on this playbook today, so I'll test this.

Thank you for opening this issue!

**Comment by ghost** [comment]
I run the playbook with become(sudo) and I got the site online and running. I am still solving a few things on my side with the user creation so I have not tested the other functionalities yet.
I changed the permissions there:
```
- name: "Creating Harbor directory... ({{ harbor_install_dir }}/harbor)"
  file:
    path: "{{ harbor_install_dir }}"
    state: directory
    mode: 0750
  when:
    - not harbor_folder_st.stat.exists or (harbor_folder_st.stat.isdir is defined and not harbor_folder_st.stat.isdir)

- name: "Uncompressing Harbor installer..."
  unarchive:
    remote_src: True
    src: /tmp/harbor.tgz
    dest: "{{ harbor_install_dir }}"
    mode: 0750
    creates: "{{ harbor_install_dir }}/harbor"
  when:
    - not harbor_folder_st.stat.exists or (harbor_folder_st.stat.isdir is defined and not harbor_folder_st.stat.isdir)
```

**Comment by nicholasamorim** [comment]
I get it running but when I stop and start it using `docker-compose`, nginx always complains. I just ran with 0750 and went great, but as soon as I stop and start, nginx goes: 

`open() "/etc/nginx/nginx.conf" failed (13: Permission denied)`

**Comment by ghost** [comment]
I see. Would it work if  `group: docker` is added? So then the files are not root:root but root:docker
```
- name: "Creating Harbor directory... ({{ harbor_install_dir }}/harbor)"
  file:
    path: "{{ harbor_install_dir }}"
    state: directory
    mode: 0750
    group: docker
  when:
    - not harbor_folder_st.stat.exists or (harbor_folder_st.stat.isdir is defined and not harbor_folder_st.stat.isdir)

- name: "Uncompressing Harbor installer..."
  unarchive:
    remote_src: True
    src: /tmp/harbor.tgz
    dest: "{{ harbor_install_dir }}"
    mode: 0750
    group: docker
    creates: "{{ harbor_install_dir }}/harbor"
  when:
    - not harbor_folder_st.stat.exists or (harbor_folder_st.stat.isdir is defined and not harbor_folder_st.stat.isdir)
```
